#!/usr/bin/env python3
"""Build script: creates all Trends Tab files (8 queries + 1 widget)."""

import json, os

BASE   = '/Users/ferdinandbarenfanger/heyjobs-smb-dashboard'
TDIR   = f'{BASE}/pages/Trends'

OWNER_IDS = ("'0059L000000JKG9QAO','005W7000000zmHSIAY','005W7000009NCmTIAW',"
             "'0051v00000BjKXAAA3','0059L000000JKFlQAO','005W7000005SzP3IAK',"
             "'005W7000005SxQTIA0','005W7000004vQt7IAE','005W7000005WNTFIA4',"
             "'0059L000000IlsvQAC','0059L000000JKGDQA4','005W7000002HR5tIAG',"
             "'005W70000048JRNIA2','005W7000003UovJIAS','0059L000000JKGOQA4',"
             "'005W7000004vQptIAE','005W7000005SxezIAC',"
             "'005W7000006RaC1IAK','005W7000006fJw5IAE','005W70000064mKSIAY',"
             "'005W7000006fJrFIAU','0059L000000JKGSQA4','005W70000071E6XIAU'")

# ── Query factory ─────────────────────────────────────────────────────────────
def make_query(name, soql):
    dpath = f'{TDIR}/queries/{name}'
    os.makedirs(dpath, exist_ok=True)
    meta = {
        "gitSyncId": f"Trends_{name}",
        "id": f"Trends_{name}",
        "pluginId": "salesforce",
        "pluginType": "EXTERNAL_SAAS",
        "unpublishedAction": {
            "actionConfiguration": {
                "encodeParamsToggle": True,
                "formData": {
                    "CUSTOM_ACTION": {
                        "headers": [{"key": "", "value": ""}],
                        "method": "GET",
                        "params": [{"key": "q", "value": soql}],
                        "path": f"query/?q={soql}"
                    },
                    "command": "CUSTOM_ACTION"
                },
                "paginationType": "NONE",
                "timeoutInMillisecond": 60000
            },
            "confirmBeforeExecute": False,
            "datasource": {
                "id": "SalesforceAPI",
                "isAutoGenerated": False,
                "name": "SalesforceAPI",
                "pluginId": "salesforce"
            },
            "dynamicBindingPathList": [],
            "name": name,
            "pageId": "Trends",
            "runBehaviour": "ON_PAGE_LOAD",
            "userSetOnLoad": True
        }
    }
    with open(f'{dpath}/metadata.json', 'w', encoding='utf-8') as f:
        json.dump(meta, f, ensure_ascii=False, indent=4)
    print(f'  Created {name}')

# ── 8 SOQL queries ────────────────────────────────────────────────────────────
QUERIES = [
    ('Q_Trends_Bookings',
     f"SELECT OwnerId, CALENDAR_YEAR(dateTimestampContractreceived__c), CALENDAR_MONTH(dateTimestampContractreceived__c), SUM(Amount), COUNT(Id) FROM Opportunity WHERE IsWon = true AND dateTimestampContractreceived__c >= 2025-01-01 AND RecordType.Name != 'Customer Self Service' AND OwnerId IN ({OWNER_IDS}) GROUP BY OwnerId, CALENDAR_YEAR(dateTimestampContractreceived__c), CALENDAR_MONTH(dateTimestampContractreceived__c) ORDER BY CALENDAR_YEAR(dateTimestampContractreceived__c), CALENDAR_MONTH(dateTimestampContractreceived__c)"),

    ('Q_Trends_Pilots',
     f"SELECT OwnerId, CALENDAR_YEAR(dateTimestampContractreceived__c), CALENDAR_MONTH(dateTimestampContractreceived__c), COUNT(Id) FROM Opportunity WHERE IsWon = true AND Winback_Pilot__c > 0 AND dateTimestampContractreceived__c >= 2025-01-01 AND RecordType.Name != 'Customer Self Service' AND OwnerId IN ({OWNER_IDS}) GROUP BY OwnerId, CALENDAR_YEAR(dateTimestampContractreceived__c), CALENDAR_MONTH(dateTimestampContractreceived__c) ORDER BY CALENDAR_YEAR(dateTimestampContractreceived__c), CALENDAR_MONTH(dateTimestampContractreceived__c)"),

    ('Q_Trends_Calls',
     f"SELECT OwnerId, CALENDAR_YEAR(ActivityDate), CALENDAR_MONTH(ActivityDate), COUNT(Id) FROM Task WHERE (TaskSubtype = 'Call' OR CallType = 'Inbound' OR CallType = 'Outbound') AND ActivityDate >= 2025-01-01 AND OwnerId IN ({OWNER_IDS}) GROUP BY OwnerId, CALENDAR_YEAR(ActivityDate), CALENDAR_MONTH(ActivityDate) ORDER BY CALENDAR_YEAR(ActivityDate), CALENDAR_MONTH(ActivityDate)"),

    ('Q_Trends_QualCalls',
     f"SELECT OwnerId, CALENDAR_YEAR(ActivityDate), CALENDAR_MONTH(ActivityDate), COUNT(Id) FROM Task WHERE (TaskSubtype = 'Call' OR CallType = 'Inbound' OR CallType = 'Outbound') AND CallDurationInSeconds >= 120 AND ActivityDate >= 2025-01-01 AND OwnerId IN ({OWNER_IDS}) GROUP BY OwnerId, CALENDAR_YEAR(ActivityDate), CALENDAR_MONTH(ActivityDate) ORDER BY CALENDAR_YEAR(ActivityDate), CALENDAR_MONTH(ActivityDate)"),

    ('Q_Trends_Emails',
     f"SELECT OwnerId, CALENDAR_YEAR(ActivityDate), CALENDAR_MONTH(ActivityDate), COUNT(Id) FROM Task WHERE TaskSubtype = 'Email' AND ActivityDate >= 2025-01-01 AND OwnerId IN ({OWNER_IDS}) GROUP BY OwnerId, CALENDAR_YEAR(ActivityDate), CALENDAR_MONTH(ActivityDate) ORDER BY CALENDAR_YEAR(ActivityDate), CALENDAR_MONTH(ActivityDate)"),

    ('Q_Trends_Meetings',
     f"SELECT OwnerId, CALENDAR_YEAR(ActivityDate), CALENDAR_MONTH(ActivityDate), COUNT(Id) FROM Event WHERE AccountId != null AND ActivityDate >= 2025-01-01 AND OwnerId IN ({OWNER_IDS}) GROUP BY OwnerId, CALENDAR_YEAR(ActivityDate), CALENDAR_MONTH(ActivityDate) ORDER BY CALENDAR_YEAR(ActivityDate), CALENDAR_MONTH(ActivityDate)"),

    ('Q_Trends_WinLoss',
     f"SELECT OwnerId, CALENDAR_YEAR(CloseDate), CALENDAR_MONTH(CloseDate), IsWon, COUNT(Id), SUM(Amount) FROM Opportunity WHERE IsClosed = true AND CloseDate >= 2025-01-01 AND RecordType.Name != 'Customer Self Service' AND OwnerId IN ({OWNER_IDS}) GROUP BY OwnerId, CALENDAR_YEAR(CloseDate), CALENDAR_MONTH(CloseDate), IsWon ORDER BY CALENDAR_YEAR(CloseDate), CALENDAR_MONTH(CloseDate)"),

    ('Q_Trends_OppsCreated',
     f"SELECT OwnerId, CALENDAR_YEAR(CreatedDate), CALENDAR_MONTH(CreatedDate), COUNT(Id) FROM Opportunity WHERE RecordType.Name != 'Customer Self Service' AND CreatedDate >= 2025-01-01T00:00:00Z AND OwnerId IN ({OWNER_IDS}) GROUP BY OwnerId, CALENDAR_YEAR(CreatedDate), CALENDAR_MONTH(CreatedDate) ORDER BY CALENDAR_YEAR(CreatedDate), CALENDAR_MONTH(CreatedDate)"),
]

# ── Widget HTML/CSS/JS ────────────────────────────────────────────────────────

WIDGET_CSS = r"""
.app {
  height: calc(var(--appsmith-ui-height) * 1px);
  width: calc(var(--appsmith-ui-width) * 1px);
  overflow-y: auto;
  overflow-x: hidden;
  font-family: 'Nunito', 'Inter', sans-serif;
  background: #f8fafc;
  box-sizing: border-box;
  padding: 0;
}
.ctip {
  position: fixed;
  background: #1e293b;
  color: #fff;
  font-size: 11px;
  padding: 5px 9px;
  border-radius: 6px;
  pointer-events: none;
  z-index: 99999;
  max-width: 280px;
  white-space: pre-wrap;
  display: none;
}
.ctip.show { display: block; }
"""

WIDGET_JS = r"""appsmith.onReady(() => {
  appsmith.onModelChange((model) => {
    if (typeof render === 'function') render(model || {});
  });
  if (typeof render === 'function') render(appsmith.model || {});
});
(function(){
  var tip=document.createElement('div');tip.className='ctip';document.body.appendChild(tip);
  document.body.addEventListener('mouseenter',function(e){
    var el=e.target.closest('[title]');if(!el)return;
    el.dataset.tip=el.getAttribute('title');el.removeAttribute('title');
    tip.textContent=el.dataset.tip;tip.classList.add('show');
  },true);
  document.body.addEventListener('mousemove',function(e){
    if(!tip.classList.contains('show'))return;
    var x=e.clientX+12,y=e.clientY+12;
    if(x+tip.offsetWidth>window.innerWidth)x=e.clientX-tip.offsetWidth-8;
    if(y+tip.offsetHeight>window.innerHeight)y=e.clientY-tip.offsetHeight-8;
    tip.style.left=x+'px';tip.style.top=y+'px';
  },true);
  document.body.addEventListener('mouseleave',function(e){
    var el=e.target;if(!el.dataset||!el.dataset.tip)return;
    el.setAttribute('title',el.dataset.tip);delete el.dataset.tip;
    tip.classList.remove('show');
  },true);
})();
"""

WIDGET_HTML = r"""<!DOCTYPE html>
<html lang="de">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link href="https://fonts.googleapis.com/css2?family=Nunito:wght@400;500;600;700;800&display=swap" rel="stylesheet">
<style>
:root {
  --green:#22c55e; --amber:#f59e0b; --red:#ef4444; --blue:#3b82f6;
  --wolves:#6366f1; --titans:#0ea5e9; --locos:#f59e0b;
  --bench:#94a3b8;
  --text-1:#0f172a; --text-2:#475569; --text-3:#94a3b8;
  --surface:#fff; --border:#e2e8f0; --bg:#f8fafc;
}
*{box-sizing:border-box;margin:0;padding:0;}
body{font-family:'Nunito',sans-serif;background:var(--bg);color:var(--text-1);font-size:13px;}

/* ── Filter bar ── */
#filters{
  position:sticky;top:0;z-index:100;
  background:var(--surface);border-bottom:1px solid var(--border);
  padding:10px 16px;display:flex;align-items:center;gap:10px;flex-wrap:wrap;
}
.team-tabs{display:flex;gap:4px;}
.team-tab{
  padding:5px 12px;border-radius:20px;border:1px solid var(--border);
  background:transparent;cursor:pointer;font-size:12px;font-weight:600;
  color:var(--text-2);transition:all .15s;white-space:nowrap;
}
.team-tab.active{background:var(--text-1);color:#fff;border-color:var(--text-1);}
.team-tab[data-team="wolves"].active{background:var(--wolves);border-color:var(--wolves);}
.team-tab[data-team="titans"].active{background:var(--titans);border-color:var(--titans);}
.team-tab[data-team="locos"].active{background:var(--locos);border-color:var(--locos);}

.f-select{
  padding:5px 10px;border-radius:8px;border:1px solid var(--border);
  background:var(--surface);font-size:12px;color:var(--text-1);cursor:pointer;
  font-family:inherit;
}
.range-tabs{display:flex;gap:3px;}
.range-tab{
  padding:4px 10px;border-radius:6px;border:1px solid var(--border);
  background:transparent;cursor:pointer;font-size:11px;font-weight:600;
  color:var(--text-2);transition:all .15s;
}
.range-tab.active{background:var(--blue);color:#fff;border-color:var(--blue);}

.gran-toggle,.bench-toggle{display:flex;gap:3px;}
.toggle-btn{
  padding:4px 8px;border-radius:6px;border:1px solid var(--border);
  background:transparent;cursor:pointer;font-size:11px;color:var(--text-2);
  font-weight:600;transition:all .15s;
}
.toggle-btn.active{background:var(--text-2);color:#fff;border-color:var(--text-2);}
.bench-on .toggle-btn.active{background:#64748b;}

.f-sep{width:1px;height:22px;background:var(--border);margin:0 2px;}
.f-label{font-size:11px;color:var(--text-3);font-weight:600;white-space:nowrap;}

/* ── Main content ── */
#main{padding:16px;}
.section{margin-bottom:24px;}
.section-title{
  font-size:11px;font-weight:800;color:var(--text-3);text-transform:uppercase;
  letter-spacing:.08em;margin-bottom:12px;padding-left:2px;
}
.chart-grid-2{display:grid;grid-template-columns:1fr 1fr;gap:16px;}
.chart-grid-4{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;}
.chart-card{
  background:var(--surface);border:1px solid var(--border);border-radius:12px;
  padding:14px 14px 10px;
}
.chart-label{font-size:11px;font-weight:700;color:var(--text-2);margin-bottom:10px;}
.chart-sub{font-size:10px;color:var(--text-3);margin-left:6px;font-weight:500;}
.chart-wrap{position:relative;height:200px;}
.chart-wrap.small{height:130px;}
canvas{display:block;}

/* ── Loading / Empty ── */
#loading{
  display:flex;align-items:center;justify-content:center;
  height:400px;flex-direction:column;gap:12px;color:var(--text-3);font-size:13px;
}
.spinner{
  width:32px;height:32px;border:3px solid #e2e8f0;
  border-top-color:var(--blue);border-radius:50%;
  animation:spin .7s linear infinite;
}
@keyframes spin{to{transform:rotate(360deg);}}

/* ── Piloten caveat ── */
.pil-caveat{
  font-size:10px;color:var(--text-3);text-align:center;
  margin-top:4px;font-style:italic;
}
</style>
</head>
<body>

<!-- Filter bar -->
<div id="filters">
  <div class="team-tabs">
    <button class="team-tab active" data-team="all" onclick="setTeam('all')">Alle Teams</button>
    <button class="team-tab" data-team="wolves" onclick="setTeam('wolves')">🐺 Wolves</button>
    <button class="team-tab" data-team="titans" onclick="setTeam('titans')">⚡ Titans</button>
    <button class="team-tab" data-team="locos" onclick="setTeam('locos')">🔥 Locos</button>
  </div>
  <div class="f-sep"></div>
  <select class="f-select" id="repSel" onchange="setRep(this.value)">
    <option value="all">Alle Reps</option>
  </select>
  <div class="f-sep"></div>
  <div class="range-tabs" id="rangeTabs">
    <button class="range-tab active" data-range="all" onclick="setRange('all')">Alles</button>
    <button class="range-tab" data-range="2026" onclick="setRange('2026')">2026</button>
    <button class="range-tab" data-range="q1-2026" onclick="setRange('q1-2026')">Q1 2026</button>
    <button class="range-tab" data-range="2025" onclick="setRange('2025')">2025</button>
    <button class="range-tab" data-range="l6m" onclick="setRange('l6m')">L6M</button>
  </div>
  <div class="f-sep"></div>
  <span class="f-label">Granularität</span>
  <div class="gran-toggle">
    <button class="toggle-btn active" data-gran="month" onclick="setGran('month')">Monat</button>
    <button class="toggle-btn" data-gran="quarter" onclick="setGran('quarter')">Quartal</button>
  </div>
  <div class="f-sep"></div>
  <div class="gran-toggle">
    <button class="toggle-btn" id="benchBtn" onclick="toggleBench()">Benchmark</button>
  </div>
</div>

<!-- Main content -->
<div id="main">
  <div id="loading"><div class="spinner"></div>Daten werden geladen…</div>
  <div id="charts" style="display:none">
    <!-- Section 1: Ergebnisse -->
    <div class="section">
      <div class="section-title">Ergebnisse</div>
      <div class="chart-grid-2">
        <div class="chart-card">
          <div class="chart-label">Bookings ARR <span class="chart-sub">in €k/Monat</span></div>
          <div class="chart-wrap"><canvas id="cBk"></canvas></div>
        </div>
        <div class="chart-card">
          <div class="chart-label">Piloten Closings <span class="chart-sub"># Abschlüsse/Monat</span></div>
          <div class="chart-wrap"><canvas id="cPil"></canvas></div>
          <div class="pil-caveat" id="pilCaveat"></div>
        </div>
      </div>
    </div>
    <!-- Section 2: Win Rate & Deals -->
    <div class="section">
      <div class="section-title">Win Rate &amp; Deals</div>
      <div class="chart-grid-2">
        <div class="chart-card">
          <div class="chart-label">Win Rate <span class="chart-sub">% gewonnene Deals</span></div>
          <div class="chart-wrap"><canvas id="cWr"></canvas></div>
        </div>
        <div class="chart-card">
          <div class="chart-label">Won / Lost Deals <span class="chart-sub">Anzahl</span></div>
          <div class="chart-wrap"><canvas id="cWl"></canvas></div>
        </div>
      </div>
    </div>
    <!-- Section 3: Neue Opportunities -->
    <div class="section">
      <div class="section-title">Pipeline</div>
      <div class="chart-grid-2">
        <div class="chart-card">
          <div class="chart-label">Neue Opportunities <span class="chart-sub">erstellt/Monat</span></div>
          <div class="chart-wrap"><canvas id="cOpps"></canvas></div>
        </div>
        <div class="chart-card">
          <div class="chart-label">Conversion <span class="chart-sub">Qual Rate % (QualCalls / Calls)</span></div>
          <div class="chart-wrap"><canvas id="cQr"></canvas></div>
        </div>
      </div>
    </div>
    <!-- Section 4: Aktivität -->
    <div class="section">
      <div class="section-title">Aktivität</div>
      <div class="chart-grid-4">
        <div class="chart-card">
          <div class="chart-label">Calls</div>
          <div class="chart-wrap small"><canvas id="cCalls"></canvas></div>
        </div>
        <div class="chart-card">
          <div class="chart-label">QualCalls <span class="chart-sub">≥2 Min</span></div>
          <div class="chart-wrap small"><canvas id="cQcalls"></canvas></div>
        </div>
        <div class="chart-card">
          <div class="chart-label">E-Mails</div>
          <div class="chart-wrap small"><canvas id="cEmails"></canvas></div>
        </div>
        <div class="chart-card">
          <div class="chart-label">Meetings</div>
          <div class="chart-wrap small"><canvas id="cMtg"></canvas></div>
        </div>
      </div>
    </div>
  </div>
</div>

<script src="https://cdn.jsdelivr.net/npm/chart.js@4.4.0/dist/chart.umd.min.js"></script>
<script>
// ── Rep & Team definitions ───────────────────────────────────────────────────
var REPS = [
  {id:'0059L000000JKG9QAO', name:'Kühne',       team:'wolves'},
  {id:'005W7000000zmHSIAY', name:'Byer',         team:'wolves'},
  {id:'005W7000009NCmTIAW', name:'Kaulbach',     team:'wolves'},
  {id:'0051v00000BjKXAAA3', name:'Canbolat',     team:'titans'},
  {id:'0059L000000JKFlQAO', name:'Stange',       team:'titans'},
  {id:'005W7000005SzP3IAK', name:'Siewert',      team:'titans'},
  {id:'005W7000005SxQTIA0', name:'Dalis',        team:'titans'},
  {id:'005W7000004vQt7IAE', name:'Eismann',      team:'titans'},
  {id:'005W7000005WNTFIA4', name:'Wahl',         team:'titans'},
  {id:'0059L000000IlsvQAC', name:'R. Schulz',    team:'locos'},
  {id:'0059L000000JKGDQA4', name:'Kizilkaya',    team:'locos'},
  {id:'005W7000002HR5tIAG', name:'Buga',         team:'locos'},
  {id:'005W70000048JRNIA2', name:'Konrad',       team:'locos'},
  {id:'005W7000003UovJIAS', name:'Beck',         team:'locos'},
  {id:'0059L000000JKGOQA4', name:'P. Schmidt',   team:'locos'},
  {id:'005W7000004vQptIAE', name:'Hoffmann',     team:'locos'},
  // excluded (trackable in Trends)
  {id:'005W7000005SxezIAC', name:'✕ Wilsenack',  team:'wolves', excl:true},
  // leavers
  {id:'005W7000006RaC1IAK', name:'✕ Kaulbach',   team:null, leaver:true},
  {id:'005W7000006fJw5IAE', name:'✕ Moya',       team:null, leaver:true},
  {id:'005W70000064mKSIAY', name:'✕ Jaskowsky',  team:null, leaver:true},
  {id:'005W7000006fJrFIAU', name:'✕ v.Ritter',   team:null, leaver:true},
  {id:'0059L000000JKGSQA4', name:'✕ Soestmeyer', team:null, leaver:true},
  {id:'005W70000071E6XIAU', name:'✕ Pflug',       team:null, leaver:true},
];

var TEAM_COLORS = {wolves:'#6366f1', titans:'#0ea5e9', locos:'#f59e0b'};
var TEAM_LABELS = {wolves:'🐺 Wolves', titans:'⚡ Titans', locos:'🔥 Locos'};
var BENCH_COLOR = '#94a3b8';

// ── State ────────────────────────────────────────────────────────────────────
var S = { team:'all', rep:'all', range:'all', gran:'month', bench:false };
var MODEL = {};
var CHARTS = {};

// ── Range helpers ────────────────────────────────────────────────────────────
function rangeFromTo(range) {
  var now = new Date();
  var curY = now.getFullYear(), curM = now.getMonth()+1;
  var nowKey = curY+'-'+String(curM).padStart(2,'0');

  if (range==='all')      return ['2025-01', nowKey];
  if (range==='2026')     return ['2026-01', nowKey];
  if (range==='q1-2026')  return ['2026-01', '2026-03'];
  if (range==='2025')     return ['2025-01', '2025-12'];
  if (range==='l6m') {
    var d = new Date(now); d.setMonth(d.getMonth()-5);
    return [d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0'), nowKey];
  }
  return ['2025-01', nowKey];
}

function monthRange(from, to) {
  var out=[]; var [y,m]=from.split('-').map(Number);
  var [ey,em]=to.split('-').map(Number);
  while(y<ey||(y===ey&&m<=em)){
    out.push(y+'-'+String(m).padStart(2,'0'));
    m++; if(m>12){m=1;y++;}
  }
  return out;
}

function toQuarterLabels(months) {
  var seen={}, out=[];
  months.forEach(function(mo){
    var[y,m]=mo.split('-').map(Number);
    var k=y+' Q'+Math.ceil(m/3);
    if(!seen[k]){seen[k]=1;out.push(k);}
  });
  return out;
}

// ── Data helpers ─────────────────────────────────────────────────────────────
// Build {repId: {yyyymm: val}}
function buildMatrix(records, valField) {
  var m={};
  (records||[]).forEach(function(r){
    var id=r.OwnerId, yr=r.expr0, mo=String(r.expr1).padStart(2,'0');
    var k=yr+'-'+mo, v=Number(r[valField]||0);
    if(!m[id]) m[id]={};
    m[id][k]=(m[id][k]||0)+v;
  });
  return m;
}

// Win/Loss matrix: {repId: {yyyymm: {won, lost, wonAmt, lostAmt}}}
function buildWLMatrix(records) {
  var m={};
  (records||[]).forEach(function(r){
    var id=r.OwnerId, yr=r.expr0, mo=String(r.expr1).padStart(2,'0');
    var k=yr+'-'+mo;
    if(!m[id]) m[id]={};
    if(!m[id][k]) m[id][k]={won:0,lost:0,wonAmt:0,lostAmt:0};
    var cnt=Number(r.expr2||0), amt=Number(r.expr3||0);
    if(r.IsWon){m[id][k].won+=cnt;m[id][k].wonAmt+=amt;}
    else{m[id][k].lost+=cnt;m[id][k].lostAmt+=amt;}
  });
  return m;
}

// Aggregate rep data to a single series (sum across repIds)
function sumMatrix(matrix, repIds, months) {
  return months.map(function(mo){
    var s=0;
    repIds.forEach(function(id){ s+=(matrix[id]&&matrix[id][mo])||0; });
    return s;
  });
}

// Aggregate to quarters
function sumToQuarters(matrix, repIds, months) {
  var qm={};
  months.forEach(function(mo){
    var[y,m]=mo.split('-').map(Number);
    var k=y+' Q'+Math.ceil(m/3);
    var s=0; repIds.forEach(function(id){s+=(matrix[id]&&matrix[id][mo])||0;});
    qm[k]=(qm[k]||0)+s;
  });
  return qm;
}

function getMonthVal(matrix, repId, months) {
  return months.map(function(mo){ return (matrix[repId]&&matrix[repId][mo])||0; });
}

function getQuarterVals(matrix, repId, months) {
  var qm={};
  months.forEach(function(mo){
    var[y,m]=mo.split('-').map(Number);
    var k=y+' Q'+Math.ceil(m/3);
    qm[k]=(qm[k]||0)+((matrix[repId]&&matrix[repId][mo])||0);
  });
  return qm;
}

// Benchmark = average across active reps for each period
function benchmarkSeries(matrix, repIds, months, gran) {
  if(gran==='quarter'){
    var qls=toQuarterLabels(months);
    return qls.map(function(ql){
      var vals=[]; repIds.forEach(function(id){
        var qm=getQuarterVals(matrix,id,months);
        vals.push(qm[ql]||0);
      });
      return vals.length? vals.reduce(function(a,b){return a+b;},0)/vals.length : null;
    });
  }
  return months.map(function(mo){
    var vals=[]; repIds.forEach(function(id){vals.push((matrix[id]&&matrix[id][mo])||0);});
    return vals.length? vals.reduce(function(a,b){return a+b;},0)/vals.length : null;
  });
}

// Get active rep IDs for a team (or all teams)
function getActiveRepIds(team) {
  return REPS.filter(function(r){return !r.leaver&&!r.excl&&(team==='all'||r.team===team);})
             .map(function(r){return r.id;});
}

// ── Build chart datasets based on current state ──────────────────────────────
function buildDatasets(matrix, months, valField, opts) {
  opts = opts||{};
  var team=S.team, rep=S.rep, gran=S.gran, bench=S.bench;
  var datasets=[];
  var labels = gran==='quarter' ? toQuarterLabels(months) : months.map(niceMonth);

  function makeVals(id) {
    if(gran==='quarter'){
      var qls=toQuarterLabels(months), qm=getQuarterVals(matrix,id,months);
      return qls.map(function(k){return qm[k]||0;});
    }
    return getMonthVal(matrix,id,months);
  }

  if(rep!=='all') {
    // Single rep line
    var r=REPS.find(function(x){return x.id===rep;});
    datasets.push({
      label: r?r.name:'Rep',
      data: makeVals(rep),
      borderColor: r&&r.team?TEAM_COLORS[r.team]:'#64748b',
      backgroundColor: 'transparent',
      borderWidth: 2.5, pointRadius: 3, tension: .3,
    });
    // Benchmark for that team
    if(bench && r && r.team) {
      var peers=getActiveRepIds(r.team);
      datasets.push({
        label:'Benchmark '+TEAM_LABELS[r.team],
        data: benchmarkSeries(matrix,peers,months,gran),
        borderColor: BENCH_COLOR, backgroundColor:'transparent',
        borderWidth:1.5, borderDash:[4,4], pointRadius:0, tension:.3,
      });
    }
  } else if(team!=='all') {
    // Individual rep lines for one team
    var teamReps=REPS.filter(function(r){return !r.leaver&&!r.excl&&r.team===team;});
    teamReps.forEach(function(r,i){
      var col=TEAM_COLORS[team];
      var alpha=[1,.75,.55,.38,.25,.18][i]||.15;
      datasets.push({
        label: r.name,
        data: makeVals(r.id),
        borderColor: hexAlpha(col,alpha<.5?Math.max(alpha,.35):alpha),
        backgroundColor:'transparent',
        borderWidth: alpha>0.6?2.5:1.5, pointRadius:alpha>0.6?3:2, tension:.3,
      });
    });
    // Leavers as dashed
    REPS.filter(function(r){return r.leaver;}).forEach(function(r){
      var vals=makeVals(r.id);
      if(vals.every(function(v){return v===0;})) return; // skip empty
      datasets.push({
        label:r.name, data:vals,
        borderColor:'#cbd5e1', backgroundColor:'transparent',
        borderWidth:1, borderDash:[3,5], pointRadius:0, tension:.3,
      });
    });
    if(bench){
      var allIds=getActiveRepIds(team);
      datasets.push({
        label:'Team Gesamt',
        data: gran==='quarter'
          ? toQuarterLabels(months).map(function(ql){var s=0;allIds.forEach(function(id){var q=getQuarterVals(matrix,id,months);s+=q[ql]||0;});return s;})
          : months.map(function(mo){var s=0;allIds.forEach(function(id){s+=(matrix[id]&&matrix[id][mo])||0;});return s;}),
        borderColor:'#1e293b', backgroundColor:'transparent',
        borderWidth:2.5, borderDash:[6,3], pointRadius:0, tension:.3,
      });
    }
  } else {
    // Team aggregate lines
    ['wolves','titans','locos'].forEach(function(t){
      var ids=getActiveRepIds(t);
      var vals = gran==='quarter'
        ? toQuarterLabels(months).map(function(ql){var s=0;ids.forEach(function(id){var q=getQuarterVals(matrix,id,months);s+=q[ql]||0;});return s;})
        : months.map(function(mo){var s=0;ids.forEach(function(id){s+=(matrix[id]&&matrix[id][mo])||0;});return s;});
      datasets.push({
        label:TEAM_LABELS[t], data:vals,
        borderColor:TEAM_COLORS[t], backgroundColor:'transparent',
        borderWidth:2.5, pointRadius:3, tension:.3,
      });
    });
    if(bench){
      var allIds2=getActiveRepIds('all');
      var benchVals = gran==='quarter'
        ? toQuarterLabels(months).map(function(ql){var s=0;allIds2.forEach(function(id){var q=getQuarterVals(matrix,id,months);s+=q[ql]||0;});return s/3;})
        : months.map(function(mo){var s=0;allIds2.forEach(function(id){s+=(matrix[id]&&matrix[id][mo])||0;});return s/3;});
      datasets.push({
        label:'Ø Team',data:benchVals,
        borderColor:BENCH_COLOR, backgroundColor:'transparent',
        borderWidth:1.5, borderDash:[4,4], pointRadius:0, tension:.3,
      });
    }
  }
  return {labels:labels, datasets:datasets};
}

// Win/Loss datasets (stacked bar)
function buildWLDatasets(wlMatrix, months) {
  var gran=S.gran, team=S.team, rep=S.rep;
  var repIds = rep!=='all' ? [rep] : getActiveRepIds(team==='all'?'all':team);
  var qls = gran==='quarter' ? toQuarterLabels(months) : null;

  function sumWL(field) {
    if(gran==='quarter'){
      return qls.map(function(ql){
        var s=0;
        repIds.forEach(function(id){
          months.forEach(function(mo){
            var[y,m]=mo.split('-').map(Number);
            var k=y+' Q'+Math.ceil(m/3);
            if(k!==ql)return;
            if(wlMatrix[id]&&wlMatrix[id][mo]) s+=wlMatrix[id][mo][field]||0;
          });
        });
        return s;
      });
    }
    return months.map(function(mo){
      var s=0;
      repIds.forEach(function(id){
        if(wlMatrix[id]&&wlMatrix[id][mo]) s+=wlMatrix[id][mo][field]||0;
      });
      return s;
    });
  }

  return {
    labels: gran==='quarter'?qls:months.map(niceMonth),
    datasets:[
      {label:'Won', data:sumWL('won'), backgroundColor:'#86efac', borderRadius:4},
      {label:'Lost', data:sumWL('lost'), backgroundColor:'#fca5a5', borderRadius:4},
    ]
  };
}

// Win Rate datasets
function buildWRDatasets(wlMatrix, months) {
  var gran=S.gran, team=S.team, rep=S.rep;
  var bench=S.bench;
  var qls=gran==='quarter'?toQuarterLabels(months):null;

  function wrForIds(ids, period) {
    var won=0,tot=0;
    ids.forEach(function(id){
      if(!wlMatrix[id]) return;
      var keys = gran==='quarter'
        ? months.filter(function(mo){var[y,m]=mo.split('-').map(Number);return (y+' Q'+Math.ceil(m/3))===period;})
        : [period];
      keys.forEach(function(mo){
        if(!wlMatrix[id][mo])return;
        won+=wlMatrix[id][mo].won||0;
        tot+=(wlMatrix[id][mo].won||0)+(wlMatrix[id][mo].lost||0);
      });
    });
    return tot>0?Math.round(won/tot*100):null;
  }

  var periods=gran==='quarter'?qls:months;
  var labels=gran==='quarter'?qls:months.map(niceMonth);
  var datasets=[];

  if(rep!=='all'){
    var r=REPS.find(function(x){return x.id===rep;});
    datasets.push({
      label:r?r.name:'Rep',
      data:periods.map(function(p){return wrForIds([rep],p);}),
      borderColor:r&&r.team?TEAM_COLORS[r.team]:'#64748b',
      backgroundColor:'transparent', borderWidth:2.5, pointRadius:3, tension:.3,
      spanGaps:true,
    });
  } else if(team!=='all'){
    var teamReps2=REPS.filter(function(r){return !r.leaver&&!r.excl&&r.team===team;});
    teamReps2.forEach(function(r,i){
      var a=[1,.7,.5,.35,.25,.18][i]||.15;
      datasets.push({
        label:r.name,
        data:periods.map(function(p){return wrForIds([r.id],p);}),
        borderColor:hexAlpha(TEAM_COLORS[team],Math.max(a,.35)),
        backgroundColor:'transparent', borderWidth:a>0.6?2.5:1.5,
        pointRadius:a>0.6?3:2, tension:.3, spanGaps:true,
      });
    });
  } else {
    ['wolves','titans','locos'].forEach(function(t){
      var ids=getActiveRepIds(t);
      datasets.push({
        label:TEAM_LABELS[t],
        data:periods.map(function(p){return wrForIds(ids,p);}),
        borderColor:TEAM_COLORS[t], backgroundColor:'transparent',
        borderWidth:2.5, pointRadius:3, tension:.3, spanGaps:true,
      });
    });
  }
  return {labels:labels, datasets:datasets};
}

// ── Chart.js setup ────────────────────────────────────────────────────────────
Chart.defaults.font.family = "'Nunito', sans-serif";
Chart.defaults.font.size = 11;
Chart.defaults.color = '#64748b';

function makeChart(id, type, data, opts) {
  if(CHARTS[id]) CHARTS[id].destroy();
  var ctx=document.getElementById(id);
  if(!ctx) return;
  var defaults = {
    responsive:true, maintainAspectRatio:false,
    plugins:{
      legend:{display: data.datasets.length>1, position:'top',
        labels:{boxWidth:12, padding:10, font:{size:10}}},
      tooltip:{mode:'index',intersect:false,
        callbacks:{label:function(c){
          var v=c.parsed.y;
          if(v===null||v===undefined)return null;
          return c.dataset.label+': '+(opts&&opts.pct?v.toFixed(1)+'%':
            opts&&opts.eur?'€'+(v/1000).toFixed(1)+'k':Math.round(v));
        }}
      }
    },
    scales:{
      x:{grid:{display:false}, ticks:{maxRotation:45}},
      y:{grid:{color:'#f1f5f9'}, ticks:{
        callback:function(v){
          return (opts&&opts.pct)?v+'%':
                 (opts&&opts.eur)?(v/1000).toFixed(0)+'k':v;
        }
      }}
    },
    interaction:{mode:'index',intersect:false},
  };
  if(opts&&opts.stacked){
    defaults.scales.y.stacked=true;
    defaults.scales.x.stacked=true;
  }
  CHARTS[id]=new Chart(ctx,{type:type,data:data,options:Object.assign(defaults,opts&&opts.extra||{})});
}

// ── Piloten null-out before 2026-01 ──────────────────────────────────────────
function applyPilNulls(datasets, labels) {
  datasets.forEach(function(ds){
    ds.data=ds.data.map(function(v,i){
      // convert label back to yyyymm
      var raw=labels[i]; // could be 'Jan 25' or '2025 Q1' or '2025-01'
      var isPost2026=false;
      if(raw.indexOf('2026')>=0||raw.indexOf('2027')>=0) isPost2026=true;
      return isPost2026?v:null;
    });
  });
}

// ── Render all charts ─────────────────────────────────────────────────────────
function renderAll() {
  var [from,to]=rangeFromTo(S.range);
  var months=monthRange(from,to);

  // parse model data
  var bkMatrix  =buildMatrix(MODEL.bk||[],  'expr2');
  var pilMatrix  =buildMatrix(MODEL.pil||[], 'expr2');
  var callMatrix =buildMatrix(MODEL.calls||[],'expr2');
  var qcMatrix   =buildMatrix(MODEL.qcalls||[],'expr2');
  var emailMatrix=buildMatrix(MODEL.emails||[],'expr2');
  var mtgMatrix  =buildMatrix(MODEL.meetings||[],'expr2');
  var wlMatrix   =buildWLMatrix(MODEL.wl||[]);
  var oppMatrix  =buildMatrix(MODEL.opps||[],'expr2');

  // ── Bookings (€ → display as €k) ──
  var bkData=buildDatasets(bkMatrix,months,null,{});
  makeChart('cBk','line',bkData,{eur:true});

  // ── Piloten (null before 2026) ──
  var pilData=buildDatasets(pilMatrix,months,null,{});
  applyPilNulls(pilData.datasets, pilData.labels);
  makeChart('cPil','line',pilData,{});
  // Caveat
  var caveat=document.getElementById('pilCaveat');
  if(from<'2026-01') caveat.textContent='Vor 2026: Daten nicht verlässlich (Tracking ab Q1 2026)';
  else caveat.textContent='';

  // ── Win/Loss (stacked bar) ──
  makeChart('cWl','bar',buildWLDatasets(wlMatrix,months),{stacked:true});

  // ── Win Rate ──
  makeChart('cWr','line',buildWRDatasets(wlMatrix,months),{pct:true,extra:{scales:{y:{min:0,max:100}}}});

  // ── Opps Created ──
  var oppData=buildDatasets(oppMatrix,months,null,{});
  makeChart('cOpps','line',oppData,{});

  // ── Qual Rate (QualCalls / Calls × 100) ──
  var qrData=buildQRDatasets(callMatrix,qcMatrix,months);
  makeChart('cQr','line',qrData,{pct:true,extra:{scales:{y:{min:0,max:100}}}});

  // ── Activity charts ──
  makeChart('cCalls',  'line', buildDatasets(callMatrix,  months,null,{}), {});
  makeChart('cQcalls', 'line', buildDatasets(qcMatrix,    months,null,{}), {});
  makeChart('cEmails', 'line', buildDatasets(emailMatrix, months,null,{}), {});
  makeChart('cMtg',    'line', buildDatasets(mtgMatrix,   months,null,{}), {});
}

// Qual Rate datasets
function buildQRDatasets(callMatrix, qcMatrix, months) {
  var gran=S.gran, team=S.team, rep=S.rep;
  var bench=S.bench;
  var qls=gran==='quarter'?toQuarterLabels(months):null;
  var periods=gran==='quarter'?qls:months;
  var labels=gran==='quarter'?qls:months.map(niceMonth);

  function qrForIds(ids, period) {
    var calls=0, qc=0;
    ids.forEach(function(id){
      var keys=gran==='quarter'
        ? months.filter(function(mo){var[y,m]=mo.split('-').map(Number);return (y+' Q'+Math.ceil(m/3))===period;})
        : [period];
      keys.forEach(function(mo){
        calls+=(callMatrix[id]&&callMatrix[id][mo])||0;
        qc+=(qcMatrix[id]&&qcMatrix[id][mo])||0;
      });
    });
    return calls>0?Math.round(qc/calls*100):null;
  }

  var datasets=[];
  if(rep!=='all'){
    var r=REPS.find(function(x){return x.id===rep;});
    datasets.push({
      label:r?r.name:'Rep',
      data:periods.map(function(p){return qrForIds([rep],p);}),
      borderColor:r&&r.team?TEAM_COLORS[r.team]:'#64748b',
      backgroundColor:'transparent', borderWidth:2.5, pointRadius:3, tension:.3, spanGaps:true,
    });
  } else if(team!=='all'){
    var teamReps3=REPS.filter(function(r){return !r.leaver&&!r.excl&&r.team===team;});
    teamReps3.forEach(function(r,i){
      var a=[1,.7,.5,.35,.25,.18][i]||.15;
      datasets.push({
        label:r.name,
        data:periods.map(function(p){return qrForIds([r.id],p);}),
        borderColor:hexAlpha(TEAM_COLORS[team],Math.max(a,.35)),
        backgroundColor:'transparent', borderWidth:a>0.6?2.5:1.5,
        pointRadius:a>0.6?3:2, tension:.3, spanGaps:true,
      });
    });
  } else {
    ['wolves','titans','locos'].forEach(function(t){
      var ids=getActiveRepIds(t);
      datasets.push({
        label:TEAM_LABELS[t],
        data:periods.map(function(p){return qrForIds(ids,p);}),
        borderColor:TEAM_COLORS[t], backgroundColor:'transparent',
        borderWidth:2.5, pointRadius:3, tension:.3, spanGaps:true,
      });
    });
  }
  return {labels:labels, datasets:datasets};
}

// ── Utilities ─────────────────────────────────────────────────────────────────
function niceMonth(ym) {
  var[y,m]=ym.split('-').map(Number);
  var mName=['Jan','Feb','Mär','Apr','Mai','Jun','Jul','Aug','Sep','Okt','Nov','Dez'][m-1];
  return mName+' '+String(y).slice(2);
}

function hexAlpha(hex, a) {
  var r=parseInt(hex.slice(1,3),16),g=parseInt(hex.slice(3,5),16),b=parseInt(hex.slice(5,7),16);
  return 'rgba('+r+','+g+','+b+','+a+')';
}

// ── Filter setters ────────────────────────────────────────────────────────────
function setTeam(t) {
  S.team=t; S.rep='all';
  document.querySelectorAll('.team-tab').forEach(function(el){
    el.classList.toggle('active',el.dataset.team===t);
  });
  rebuildRepDropdown();
  renderAll();
}

function setRep(r) {
  S.rep=r;
  renderAll();
}

function setRange(r) {
  S.range=r;
  document.querySelectorAll('.range-tab').forEach(function(el){
    el.classList.toggle('active',el.dataset.range===r);
  });
  renderAll();
}

function setGran(g) {
  S.gran=g;
  document.querySelectorAll('.toggle-btn[data-gran]').forEach(function(el){
    el.classList.toggle('active',el.dataset.gran===g);
  });
  renderAll();
}

function toggleBench() {
  S.bench=!S.bench;
  document.getElementById('benchBtn').classList.toggle('active',S.bench);
  renderAll();
}

function rebuildRepDropdown() {
  var sel=document.getElementById('repSel');
  sel.innerHTML='<option value="all">Alle Reps</option>';
  var showReps=REPS.filter(function(r){
    return !r.leaver&&!r.excl&&(S.team==='all'||r.team===S.team);
  });
  showReps.forEach(function(r){
    var o=document.createElement('option');
    o.value=r.id; o.textContent=r.name; sel.appendChild(o);
  });
  // Leavers divider
  var leavers=REPS.filter(function(r){return r.leaver||r.excl;});
  if(leavers.length){
    var d=document.createElement('option'); d.disabled=true; d.textContent='── Ehemalige ──';
    sel.appendChild(d);
    leavers.forEach(function(r){
      var o=document.createElement('option');
      o.value=r.id; o.textContent=r.name; sel.appendChild(o);
    });
  }
}

// ── Main render entry ─────────────────────────────────────────────────────────
function render(model) {
  MODEL = model||{};
  var hasData=!!(MODEL.bk&&MODEL.bk.length>0||MODEL.calls&&MODEL.calls.length>0);
  document.getElementById('loading').style.display = hasData?'none':'flex';
  document.getElementById('charts').style.display = hasData?'block':'none';
  if(!hasData) return;
  rebuildRepDropdown();
  renderAll();
}

// Init
rebuildRepDropdown();
</script>
</body>
</html>
"""

# ── Widget JSON ───────────────────────────────────────────────────────────────
DEFAULT_MODEL = (
    "{{(function(){"
    "var _r=appsmith.store._refreshTs;"
    "function rec(q){try{return q.data.output.records||[];}catch(e){return [];}}"
    "return {"
    "bk:rec(Q_Trends_Bookings),"
    "pil:rec(Q_Trends_Pilots),"
    "calls:rec(Q_Trends_Calls),"
    "qcalls:rec(Q_Trends_QualCalls),"
    "emails:rec(Q_Trends_Emails),"
    "meetings:rec(Q_Trends_Meetings),"
    "wl:rec(Q_Trends_WinLoss),"
    "opps:rec(Q_Trends_OppsCreated),"
    "};})()}}"
)

def make_widget():
    os.makedirs(f'{TDIR}/widgets', exist_ok=True)
    widget = {
        "backgroundColor": "none",
        "borderColor": "{{appsmith.theme.borderColor}}",
        "borderRadius": "{{appsmith.theme.borderRadius}}",
        "borderWidth": "0",
        "bottomRow": 260,
        "boxShadow": "none",
        "defaultModel": DEFAULT_MODEL,
        "dynamicBindingPathList": [
            {"key": "defaultModel"},
            {"key": "theme"},
            {"key": "borderRadius"},
            {"key": "boxShadow"},
        ],
        "dynamicHeight": "FIXED",
        "dynamicTriggerPathList": [],
        "events": [],
        "isCanvas": False,
        "isLoading": False,
        "isSearchWildcard": False,
        "isVisible": True,
        "key": "2fk8pwrpyl",
        "leftColumn": 0,
        "maxDynamicHeight": 9000,
        "minDynamicHeight": 4,
        "mobileBottomRow": 260,
        "mobileLeftColumn": 0,
        "mobileRightColumn": 64,
        "mobileTopRow": 0,
        "needsErrorInfo": False,
        "onResetClick": "{{undefined}}",
        "parentColumnSpace": 19.125,
        "parentId": "0",
        "parentRowSpace": 10,
        "renderMode": "CANVAS",
        "rightColumn": 64,
        "srcDoc": {
            "css": WIDGET_CSS,
            "html": WIDGET_HTML,
            "js": WIDGET_JS,
        },
        "theme": "{{{\n  borderRadius: appsmith.theme.borderRadius,\n  boxShadow: appsmith.theme.boxShadow,\n  fontFamily: appsmith.theme.fontFamily,\n  primaryColor: appsmith.theme.colors.primaryColor,\n  backgroundColor: appsmith.theme.colors.backgroundColor,\n}}}",
        "topRow": 0,
        "type": "CUSTOM_WIDGET",
        "uncompiledSrcDoc": {
            "css": WIDGET_CSS,
            "html": WIDGET_HTML,
            "js": WIDGET_JS,
        },
        "version": 1,
        "widgetId": "trends_chart_w1",
        "widgetName": "Trends_Chart",
    }
    wpath = f'{TDIR}/widgets/Trends_Chart.json'
    with open(wpath, 'w', encoding='utf-8') as f:
        json.dump(widget, f, ensure_ascii=False, indent=2)
    print(f'  Created Trends_Chart.json ({len(WIDGET_HTML)} chars HTML)')

# ── Run ───────────────────────────────────────────────────────────────────────
print('Creating Trends queries...')
for name, soql in QUERIES:
    make_query(name, soql)

print('\nCreating Trends widget...')
make_widget()

print('\nDone. Files created:')
for name, _ in QUERIES:
    print(f'  pages/Trends/queries/{name}/metadata.json')
print('  pages/Trends/widgets/Trends_Chart.json')
