#!/usr/bin/env python3
"""
Build Q1 2026 snapshot for JS_Snapshots.js
Auto-generated by build_snapshot.py
"""

import json
import re

# ── Paths ────────────────────────────────────────────────────────────────────
BASE = "/Users/ferdinandbarenfanger/.claude/projects/-Users-ferdinandbarenfanger-SMB-Steering-Cockpit/4dbae845-26c2-4d38-be84-63cb5885dd28/tool-results"
TARGET = "/Users/ferdinandbarenfanger/heyjobs-smb-dashboard/pages/Dashboard/jsobjects/JS_Snapshots/JS_Snapshots.js"

# ── Helper: strip attributes recursively ─────────────────────────────────────
def strip_attributes(obj):
    if isinstance(obj, dict):
        return {k: strip_attributes(v) for k, v in obj.items() if k != "attributes"}
    if isinstance(obj, list):
        return [strip_attributes(item) for item in obj]
    return obj

# ── Helper: parse large SOQL tool-result file ────────────────────────────────
def parse_soql_file(path):
    with open(path, "r") as f:
        content = f.read()
    data = json.loads(content)
    text = data[0]["text"]
    marker = "SOQL query results:\n\n"
    idx = text.find(marker)
    if idx == -1:
        raise ValueError(f"Marker not found in {path}")
    json_str = text[idx + len(marker):]
    records_data = json.loads(json_str)
    records = records_data.get("records", [])
    return strip_attributes(records)

# ── 1. Load pre-cleaned JSON files ───────────────────────────────────────────
print("Loading clean_bookings.json ...")
with open(f"{BASE}/clean_bookings.json") as f:
    Q_Bookings_QTD = json.load(f)
print(f"  → {len(Q_Bookings_QTD)} records")

print("Loading clean_selfservice.json ...")
with open(f"{BASE}/clean_selfservice.json") as f:
    Q_SelfService_QTD = json.load(f)
print(f"  → {len(Q_SelfService_QTD)} records")

print("Loading clean_meetings.json ...")
with open(f"{BASE}/clean_meetings.json") as f:
    Q_Meetings_QTD = json.load(f)
print(f"  → {len(Q_Meetings_QTD)} records")

# ── 2. Process WinLoss large file ────────────────────────────────────────────
print("Parsing WinLoss file ...")
Q_WinLoss = parse_soql_file(f"{BASE}/mcp-Salesforce_DX-run_soql_query-1775040687560.txt")
print(f"  → {len(Q_WinLoss)} records")

# ── 3. Process Meetings_L30 large file ───────────────────────────────────────
print("Parsing Meetings_L30 file ...")
Q_Meetings_L30 = parse_soql_file(f"{BASE}/mcp-Salesforce_DX-run_soql_query-1775040744363.txt")
print(f"  → {len(Q_Meetings_L30)} records")

# ── 4. Inline data ───────────────────────────────────────────────────────────
Q_Calls_QTD = [{"OwnerId":"0051v00000BjKXAAA3","dialCount":1683},{"OwnerId":"0059L000000IlsvQAC","dialCount":636},{"OwnerId":"0059L000000JKFlQAO","dialCount":1341},{"OwnerId":"0059L000000JKG9QAO","dialCount":1298},{"OwnerId":"0059L000000JKGDQA4","dialCount":1302},{"OwnerId":"0059L000000JKGOQA4","dialCount":1653},{"OwnerId":"005W7000000zmHSIAY","dialCount":884},{"OwnerId":"005W7000002HR5tIAG","dialCount":1176},{"OwnerId":"005W7000003UovJIAS","dialCount":1582},{"OwnerId":"005W70000048JRNIA2","dialCount":1677},{"OwnerId":"005W7000004vQptIAE","dialCount":1326},{"OwnerId":"005W7000004vQt7IAE","dialCount":2195},{"OwnerId":"005W7000005SxQTIA0","dialCount":1821},{"OwnerId":"005W7000005SzP3IAK","dialCount":3453},{"OwnerId":"005W7000005WNTFIA4","dialCount":2348},{"OwnerId":"005W7000009NCmTIAW","dialCount":2253}]

Q_QualCalls_QTD = [{"OwnerId":"0051v00000BjKXAAA3","qualCount":258},{"OwnerId":"0059L000000IlsvQAC","qualCount":129},{"OwnerId":"0059L000000JKFlQAO","qualCount":227},{"OwnerId":"0059L000000JKG9QAO","qualCount":272},{"OwnerId":"0059L000000JKGDQA4","qualCount":215},{"OwnerId":"0059L000000JKGOQA4","qualCount":342},{"OwnerId":"005W7000000zmHSIAY","qualCount":171},{"OwnerId":"005W7000002HR5tIAG","qualCount":325},{"OwnerId":"005W7000003UovJIAS","qualCount":300},{"OwnerId":"005W70000048JRNIA2","qualCount":335},{"OwnerId":"005W7000004vQptIAE","qualCount":254},{"OwnerId":"005W7000004vQt7IAE","qualCount":399},{"OwnerId":"005W7000005SxQTIA0","qualCount":433},{"OwnerId":"005W7000005SzP3IAK","qualCount":408},{"OwnerId":"005W7000005WNTFIA4","qualCount":493},{"OwnerId":"005W7000009NCmTIAW","qualCount":154}]

Q_Emails_QTD = [{"OwnerId":"0051v00000BjKXAAA3","emailCount":675},{"OwnerId":"0059L000000IlsvQAC","emailCount":573},{"OwnerId":"0059L000000JKFlQAO","emailCount":360},{"OwnerId":"0059L000000JKG9QAO","emailCount":899},{"OwnerId":"0059L000000JKGDQA4","emailCount":971},{"OwnerId":"0059L000000JKGOQA4","emailCount":630},{"OwnerId":"005W7000000zmHSIAY","emailCount":592},{"OwnerId":"005W7000002HR5tIAG","emailCount":938},{"OwnerId":"005W7000003UovJIAS","emailCount":702},{"OwnerId":"005W70000048JRNIA2","emailCount":325},{"OwnerId":"005W7000004vQptIAE","emailCount":1009},{"OwnerId":"005W7000004vQt7IAE","emailCount":662},{"OwnerId":"005W7000005SxQTIA0","emailCount":487},{"OwnerId":"005W7000005SzP3IAK","emailCount":403},{"OwnerId":"005W7000005WNTFIA4","emailCount":432},{"OwnerId":"005W7000009NCmTIAW","emailCount":691}]

Q_Demos_QTD = [{"OwnerId":"0051v00000BjKXAAA3","demoCount":6},{"OwnerId":"0059L000000IlsvQAC","demoCount":6},{"OwnerId":"0059L000000JKFlQAO","demoCount":15},{"OwnerId":"0059L000000JKG9QAO","demoCount":32},{"OwnerId":"0059L000000JKGDQA4","demoCount":11},{"OwnerId":"0059L000000JKGOQA4","demoCount":24},{"OwnerId":"005W7000000zmHSIAY","demoCount":33},{"OwnerId":"005W7000002HR5tIAG","demoCount":19},{"OwnerId":"005W7000003UovJIAS","demoCount":12},{"OwnerId":"005W70000048JRNIA2","demoCount":32},{"OwnerId":"005W7000004vQptIAE","demoCount":12},{"OwnerId":"005W7000004vQt7IAE","demoCount":4},{"OwnerId":"005W7000005SxQTIA0","demoCount":4},{"OwnerId":"005W7000005SzP3IAK","demoCount":7},{"OwnerId":"005W7000005WNTFIA4","demoCount":16},{"OwnerId":"005W7000009NCmTIAW","demoCount":36}]

Q_Quotas = [{"QuotaOwnerId":"005W7000009NCmTIAW","QuotaOwner":{"Name":"Jan-Thore Kaulbach"},"QuotaAmount":17677,"StartDate":"2026-01-01"},{"QuotaOwnerId":"005W7000004vQt7IAE","QuotaOwner":{"Name":"Robert Eismann"},"QuotaAmount":67137,"StartDate":"2026-01-01"},{"QuotaOwnerId":"005W7000005WNTFIA4","QuotaOwner":{"Name":"Michael Wahl"},"QuotaAmount":69753,"StartDate":"2026-01-01"},{"QuotaOwnerId":"005W7000005SxQTIA0","QuotaOwner":{"Name":"Florian Dalis"},"QuotaAmount":73193,"StartDate":"2026-01-01"},{"QuotaOwnerId":"005W7000000zmHSIAY","QuotaOwner":{"Name":"Pierre Byer"},"QuotaAmount":76868,"StartDate":"2026-01-01"},{"QuotaOwnerId":"0059L000000JKGOQA4","QuotaOwner":{"Name":"Philipp Schmidt"},"QuotaAmount":107224,"StartDate":"2026-01-01"},{"QuotaOwnerId":"005W7000005SzP3IAK","QuotaOwner":{"Name":"Jane Siewert"},"QuotaAmount":109926,"StartDate":"2026-01-01"},{"QuotaOwnerId":"005W7000003UovJIAS","QuotaOwner":{"Name":"David Beck"},"QuotaAmount":113504,"StartDate":"2026-01-01"},{"QuotaOwnerId":"005W7000004vQptIAE","QuotaOwner":{"Name":"Nina Hoffmann"},"QuotaAmount":117760,"StartDate":"2026-01-01"},{"QuotaOwnerId":"0059L000000JKG9QAO","QuotaOwner":{"Name":"Alina K\u00fchne"},"QuotaAmount":125765,"StartDate":"2026-01-01"},{"QuotaOwnerId":"0059L000000IlsvQAC","QuotaOwner":{"Name":"Raven Schulz"},"QuotaAmount":135331,"StartDate":"2026-01-01"},{"QuotaOwnerId":"005W70000048JRNIA2","QuotaOwner":{"Name":"Marlies Konrad"},"QuotaAmount":138583,"StartDate":"2026-01-01"},{"QuotaOwnerId":"0059L000000JKGDQA4","QuotaOwner":{"Name":"Ebru Kizilkaya"},"QuotaAmount":144356,"StartDate":"2026-01-01"},{"QuotaOwnerId":"0059L000000JKFlQAO","QuotaOwner":{"Name":"Tamina Stange"},"QuotaAmount":145754,"StartDate":"2026-01-01"},{"QuotaOwnerId":"005W7000002HR5tIAG","QuotaOwner":{"Name":"Marius Buga"},"QuotaAmount":163157,"StartDate":"2026-01-01"},{"QuotaOwnerId":"0051v00000BjKXAAA3","QuotaOwner":{"Name":"Hikmet Canbolat"},"QuotaAmount":164013,"StartDate":"2026-01-01"}]

Q_Opps_Created_QTD = [{"CreatedById":"005W7000005WNTFIA4","oppCount":38},{"CreatedById":"005W70000048JRNIA2","oppCount":35},{"CreatedById":"005W7000000zmHSIAY","oppCount":24},{"CreatedById":"005W7000005SzP3IAK","oppCount":37},{"CreatedById":"005W7000002HR5tIAG","oppCount":44},{"CreatedById":"0059L000000JKG9QAO","oppCount":45},{"CreatedById":"0059L000000JKFlQAO","oppCount":25},{"CreatedById":"0051v00000BjKXAAA3","oppCount":34},{"CreatedById":"0059L000000IlsvQAC","oppCount":23},{"CreatedById":"005W7000004vQptIAE","oppCount":38},{"CreatedById":"005W7000003UovJIAS","oppCount":38},{"CreatedById":"005W7000009NCmTIAW","oppCount":21},{"CreatedById":"0059L000000JKGDQA4","oppCount":26},{"CreatedById":"005W7000005SxQTIA0","oppCount":19},{"CreatedById":"005W7000004vQt7IAE","oppCount":42},{"CreatedById":"0059L000000JKGOQA4","oppCount":13}]

Q_PilotOpps_QTD = [{"CreatedById":"005W7000005WNTFIA4","oppCount":34},{"CreatedById":"005W70000048JRNIA2","oppCount":17},{"CreatedById":"005W7000000zmHSIAY","oppCount":17},{"CreatedById":"005W7000005SzP3IAK","oppCount":18},{"CreatedById":"005W7000004vQptIAE","oppCount":16},{"CreatedById":"005W7000003UovJIAS","oppCount":21},{"CreatedById":"005W7000002HR5tIAG","oppCount":21},{"CreatedById":"0059L000000JKG9QAO","oppCount":25},{"CreatedById":"005W7000009NCmTIAW","oppCount":16},{"CreatedById":"0059L000000JKFlQAO","oppCount":12},{"CreatedById":"0059L000000JKGDQA4","oppCount":13},{"CreatedById":"005W7000005SxQTIA0","oppCount":11},{"CreatedById":"005W7000004vQt7IAE","oppCount":25},{"CreatedById":"0051v00000BjKXAAA3","oppCount":15},{"CreatedById":"0059L000000JKGOQA4","oppCount":6},{"CreatedById":"0059L000000IlsvQAC","oppCount":12}]

Q_Forecast_Commit = [{"OwnerId":"0051v00000BjKXAAA3","Owner":{"Name":"Hikmet Canbolat"},"ForecastAmount":115000},{"OwnerId":"0059L000000IlsvQAC","Owner":{"Name":"Raven Schulz"},"ForecastAmount":90000},{"OwnerId":"0059L000000JKFlQAO","Owner":{"Name":"Tamina Stange"},"ForecastAmount":115000},{"OwnerId":"0059L000000JKG9QAO","Owner":{"Name":"Alina K\u00fchne"},"ForecastAmount":107000},{"OwnerId":"0059L000000JKGDQA4","Owner":{"Name":"Ebru Kizilkaya"},"ForecastAmount":115000},{"OwnerId":"0059L000000JKGOQA4","Owner":{"Name":"Philipp Schmidt"},"ForecastAmount":90000},{"OwnerId":"005W7000000zmHSIAY","Owner":{"Name":"Pierre Byer"},"ForecastAmount":80500},{"OwnerId":"005W7000002HR5tIAG","Owner":{"Name":"Marius Buga"},"ForecastAmount":163200},{"OwnerId":"005W7000003UovJIAS","Owner":{"Name":"David Beck"},"ForecastAmount":155000},{"OwnerId":"005W70000048JRNIA2","Owner":{"Name":"Marlies Konrad"},"ForecastAmount":145000},{"OwnerId":"005W7000004kT37IAE","Owner":{"Name":"Jan Hinrichsen"},"ForecastAmount":446000},{"OwnerId":"005W7000004vQptIAE","Owner":{"Name":"Nina Hoffmann"},"ForecastAmount":85000},{"OwnerId":"005W7000004vQt7IAE","Owner":{"Name":"Robert Eismann"},"ForecastAmount":49000},{"OwnerId":"005W7000005SxQTIA0","Owner":{"Name":"Florian Dalis"},"ForecastAmount":22000},{"OwnerId":"005W7000005SzP3IAK","Owner":{"Name":"Jane Siewert"},"ForecastAmount":90000},{"OwnerId":"005W7000005WNTFIA4","Owner":{"Name":"Michael Wahl"},"ForecastAmount":55000},{"OwnerId":"005W7000006FAIDIA4","Owner":{"Name":"Ferdinand B\u00e4renf\u00e4nger"},"ForecastAmount":215000},{"OwnerId":"005W7000009NCmTIAW","Owner":{"Name":"Jan-Thore Kaulbach"},"ForecastAmount":15000},{"OwnerId":"005W700000AXqN3IAL","Owner":{"Name":"Philipp Bahls"},"ForecastAmount":1470000}]

Q_Forecast_Commit_Pilots = [{"OwnerId":"0051v00000BjKXAAA3","Owner":{"Name":"Hikmet Canbolat"},"ForecastQuantity":10},{"OwnerId":"0059L000000IlsvQAC","Owner":{"Name":"Raven Schulz"},"ForecastQuantity":10},{"OwnerId":"0059L000000JKFlQAO","Owner":{"Name":"Tamina Stange"},"ForecastQuantity":8},{"OwnerId":"0059L000000JKG9QAO","Owner":{"Name":"Alina K\u00fchne"},"ForecastQuantity":14},{"OwnerId":"0059L000000JKGDQA4","Owner":{"Name":"Ebru Kizilkaya"},"ForecastQuantity":13},{"OwnerId":"0059L000000JKGOQA4","Owner":{"Name":"Philipp Schmidt"},"ForecastQuantity":11},{"OwnerId":"005W7000000zmHSIAY","Owner":{"Name":"Pierre Byer"},"ForecastQuantity":6},{"OwnerId":"005W7000002HR5tIAG","Owner":{"Name":"Marius Buga"},"ForecastQuantity":17},{"OwnerId":"005W7000003UovJIAS","Owner":{"Name":"David Beck"},"ForecastQuantity":19},{"OwnerId":"005W70000048JRNIA2","Owner":{"Name":"Marlies Konrad"},"ForecastQuantity":16},{"OwnerId":"005W7000004kT37IAE","Owner":{"Name":"Jan Hinrichsen"},"ForecastQuantity":52},{"OwnerId":"005W7000004vQptIAE","Owner":{"Name":"Nina Hoffmann"},"ForecastQuantity":6},{"OwnerId":"005W7000004vQt7IAE","Owner":{"Name":"Robert Eismann"},"ForecastQuantity":8},{"OwnerId":"005W7000005SxQTIA0","Owner":{"Name":"Florian Dalis"},"ForecastQuantity":8},{"OwnerId":"005W7000005SzP3IAK","Owner":{"Name":"Jane Siewert"},"ForecastQuantity":8},{"OwnerId":"005W7000005WNTFIA4","Owner":{"Name":"Michael Wahl"},"ForecastQuantity":10},{"OwnerId":"005W7000006FAIDIA4","Owner":{"Name":"Ferdinand B\u00e4renf\u00e4nger"},"ForecastQuantity":23},{"OwnerId":"005W7000009NCmTIAW","Owner":{"Name":"Jan-Thore Kaulbach"},"ForecastQuantity":3},{"OwnerId":"005W700000AXqN3IAL","Owner":{"Name":"Philipp Bahls"},"ForecastQuantity":166}]

Q_Calls_CW = [{"OwnerId":"0051v00000BjKXAAA3","dialCount":95},{"OwnerId":"0059L000000IlsvQAC","dialCount":1},{"OwnerId":"0059L000000JKFlQAO","dialCount":79},{"OwnerId":"0059L000000JKG9QAO","dialCount":118},{"OwnerId":"0059L000000JKGDQA4","dialCount":97},{"OwnerId":"0059L000000JKGOQA4","dialCount":84},{"OwnerId":"005W7000000zmHSIAY","dialCount":15},{"OwnerId":"005W7000002HR5tIAG","dialCount":113},{"OwnerId":"005W7000003UovJIAS","dialCount":125},{"OwnerId":"005W70000048JRNIA2","dialCount":129},{"OwnerId":"005W7000004vQptIAE","dialCount":151},{"OwnerId":"005W7000004vQt7IAE","dialCount":129},{"OwnerId":"005W7000005SxQTIA0","dialCount":64},{"OwnerId":"005W7000005SzP3IAK","dialCount":238},{"OwnerId":"005W7000005WNTFIA4","dialCount":220},{"OwnerId":"005W7000009NCmTIAW","dialCount":190}]

Q_Calls_PW = [{"OwnerId":"0051v00000BjKXAAA3","dialCount":82},{"OwnerId":"0059L000000IlsvQAC","dialCount":19},{"OwnerId":"0059L000000JKFlQAO","dialCount":70},{"OwnerId":"0059L000000JKG9QAO","dialCount":68},{"OwnerId":"0059L000000JKGDQA4","dialCount":91},{"OwnerId":"0059L000000JKGOQA4","dialCount":108},{"OwnerId":"005W7000000zmHSIAY","dialCount":46},{"OwnerId":"005W7000002HR5tIAG","dialCount":61},{"OwnerId":"005W7000003UovJIAS","dialCount":157},{"OwnerId":"005W70000048JRNIA2","dialCount":133},{"OwnerId":"005W7000004vQptIAE","dialCount":101},{"OwnerId":"005W7000004vQt7IAE","dialCount":145},{"OwnerId":"005W7000005SxQTIA0","dialCount":121},{"OwnerId":"005W7000005SzP3IAK","dialCount":288},{"OwnerId":"005W7000005WNTFIA4","dialCount":184},{"OwnerId":"005W7000009NCmTIAW","dialCount":71}]

Q_QualCalls_CW = [{"OwnerId":"0051v00000BjKXAAA3","qualCount":26},{"OwnerId":"0059L000000JKFlQAO","qualCount":15},{"OwnerId":"0059L000000JKG9QAO","qualCount":27},{"OwnerId":"0059L000000JKGDQA4","qualCount":21},{"OwnerId":"0059L000000JKGOQA4","qualCount":23},{"OwnerId":"005W7000000zmHSIAY","qualCount":7},{"OwnerId":"005W7000002HR5tIAG","qualCount":36},{"OwnerId":"005W7000003UovJIAS","qualCount":25},{"OwnerId":"005W70000048JRNIA2","qualCount":17},{"OwnerId":"005W7000004vQptIAE","qualCount":37},{"OwnerId":"005W7000004vQt7IAE","qualCount":21},{"OwnerId":"005W7000005SxQTIA0","qualCount":14},{"OwnerId":"005W7000005SzP3IAK","qualCount":27},{"OwnerId":"005W7000005WNTFIA4","qualCount":37},{"OwnerId":"005W7000009NCmTIAW","qualCount":16}]

Q_QualCalls_PW = [{"OwnerId":"0051v00000BjKXAAA3","qualCount":18},{"OwnerId":"0059L000000IlsvQAC","qualCount":3},{"OwnerId":"0059L000000JKFlQAO","qualCount":13},{"OwnerId":"0059L000000JKG9QAO","qualCount":18},{"OwnerId":"0059L000000JKGDQA4","qualCount":18},{"OwnerId":"0059L000000JKGOQA4","qualCount":26},{"OwnerId":"005W7000000zmHSIAY","qualCount":8},{"OwnerId":"005W7000002HR5tIAG","qualCount":15},{"OwnerId":"005W7000003UovJIAS","qualCount":28},{"OwnerId":"005W70000048JRNIA2","qualCount":22},{"OwnerId":"005W7000004vQptIAE","qualCount":22},{"OwnerId":"005W7000004vQt7IAE","qualCount":32},{"OwnerId":"005W7000005SxQTIA0","qualCount":25},{"OwnerId":"005W7000005SzP3IAK","qualCount":37},{"OwnerId":"005W7000005WNTFIA4","qualCount":37},{"OwnerId":"005W7000009NCmTIAW","qualCount":6}]

Q_Emails_CW = [{"OwnerId":"0051v00000BjKXAAA3","emailCount":76},{"OwnerId":"0059L000000IlsvQAC","emailCount":12},{"OwnerId":"0059L000000JKFlQAO","emailCount":31},{"OwnerId":"0059L000000JKG9QAO","emailCount":63},{"OwnerId":"0059L000000JKGDQA4","emailCount":117},{"OwnerId":"0059L000000JKGOQA4","emailCount":90},{"OwnerId":"005W7000000zmHSIAY","emailCount":35},{"OwnerId":"005W7000002HR5tIAG","emailCount":106},{"OwnerId":"005W7000003UovJIAS","emailCount":78},{"OwnerId":"005W70000048JRNIA2","emailCount":45},{"OwnerId":"005W7000004vQptIAE","emailCount":145},{"OwnerId":"005W7000004vQt7IAE","emailCount":81},{"OwnerId":"005W7000005SxQTIA0","emailCount":21},{"OwnerId":"005W7000005SzP3IAK","emailCount":32},{"OwnerId":"005W7000005WNTFIA4","emailCount":55},{"OwnerId":"005W7000009NCmTIAW","emailCount":99}]

Q_Emails_PW = [{"OwnerId":"0051v00000BjKXAAA3","emailCount":122},{"OwnerId":"0059L000000IlsvQAC","emailCount":46},{"OwnerId":"0059L000000JKFlQAO","emailCount":8},{"OwnerId":"0059L000000JKG9QAO","emailCount":81},{"OwnerId":"0059L000000JKGDQA4","emailCount":119},{"OwnerId":"0059L000000JKGOQA4","emailCount":69},{"OwnerId":"005W7000000zmHSIAY","emailCount":44},{"OwnerId":"005W7000002HR5tIAG","emailCount":129},{"OwnerId":"005W7000003UovJIAS","emailCount":65},{"OwnerId":"005W70000048JRNIA2","emailCount":28},{"OwnerId":"005W7000004vQptIAE","emailCount":93},{"OwnerId":"005W7000004vQt7IAE","emailCount":70},{"OwnerId":"005W7000005SxQTIA0","emailCount":40},{"OwnerId":"005W7000005SzP3IAK","emailCount":35},{"OwnerId":"005W7000005WNTFIA4","emailCount":88},{"OwnerId":"005W7000009NCmTIAW","emailCount":63}]

Q_Calls_L30 = [{"OwnerId":"0051v00000BjKXAAA3","dialCount":461},{"OwnerId":"0059L000000IlsvQAC","dialCount":105},{"OwnerId":"0059L000000JKFlQAO","dialCount":397},{"OwnerId":"0059L000000JKG9QAO","dialCount":380},{"OwnerId":"0059L000000JKGDQA4","dialCount":363},{"OwnerId":"0059L000000JKGOQA4","dialCount":410},{"OwnerId":"005W7000000zmHSIAY","dialCount":177},{"OwnerId":"005W7000002HR5tIAG","dialCount":323},{"OwnerId":"005W7000003UovJIAS","dialCount":566},{"OwnerId":"005W70000048JRNIA2","dialCount":504},{"OwnerId":"005W7000004vQptIAE","dialCount":312},{"OwnerId":"005W7000004vQt7IAE","dialCount":719},{"OwnerId":"005W7000005SxQTIA0","dialCount":483},{"OwnerId":"005W7000005SzP3IAK","dialCount":1256},{"OwnerId":"005W7000005WNTFIA4","dialCount":815},{"OwnerId":"005W7000009NCmTIAW","dialCount":819}]

# Fix: dialCount -> qualCount for 005W7000005SxQTIA0
Q_QualCalls_L30 = [{"OwnerId":"0051v00000BjKXAAA3","qualCount":94},{"OwnerId":"0059L000000IlsvQAC","qualCount":13},{"OwnerId":"0059L000000JKFlQAO","qualCount":73},{"OwnerId":"0059L000000JKG9QAO","qualCount":92},{"OwnerId":"0059L000000JKGDQA4","qualCount":69},{"OwnerId":"0059L000000JKGOQA4","qualCount":103},{"OwnerId":"005W7000000zmHSIAY","qualCount":37},{"OwnerId":"005W7000002HR5tIAG","qualCount":95},{"OwnerId":"005W7000003UovJIAS","qualCount":98},{"OwnerId":"005W70000048JRNIA2","qualCount":87},{"OwnerId":"005W7000004vQptIAE","qualCount":72},{"OwnerId":"005W7000004vQt7IAE","qualCount":145},{"OwnerId":"005W7000005SxQTIA0","qualCount":117},{"OwnerId":"005W7000005SzP3IAK","qualCount":145},{"OwnerId":"005W7000005WNTFIA4","qualCount":147},{"OwnerId":"005W7000009NCmTIAW","qualCount":56}]

Q_Emails_L30 = [{"OwnerId":"0051v00000BjKXAAA3","emailCount":356},{"OwnerId":"0059L000000IlsvQAC","emailCount":178},{"OwnerId":"0059L000000JKFlQAO","emailCount":190},{"OwnerId":"0059L000000JKG9QAO","emailCount":281},{"OwnerId":"0059L000000JKGDQA4","emailCount":463},{"OwnerId":"0059L000000JKGOQA4","emailCount":324},{"OwnerId":"005W7000000zmHSIAY","emailCount":248},{"OwnerId":"005W7000002HR5tIAG","emailCount":496},{"OwnerId":"005W7000003UovJIAS","emailCount":318},{"OwnerId":"005W70000048JRNIA2","emailCount":126},{"OwnerId":"005W7000004vQptIAE","emailCount":316},{"OwnerId":"005W7000004vQt7IAE","emailCount":320},{"OwnerId":"005W7000005SxQTIA0","emailCount":125},{"OwnerId":"005W7000005SzP3IAK","emailCount":166},{"OwnerId":"005W7000005WNTFIA4","emailCount":272},{"OwnerId":"005W7000009NCmTIAW","emailCount":466}]

# For Q_Meetings_CW and Q_Meetings_PW we need to extract from Q_Meetings_L30 by date range
# CW: 2026-03-23 to 2026-03-29
# PW: 2026-03-16 to 2026-03-22
Q_Meetings_CW = [r for r in Q_Meetings_L30 if "2026-03-23" <= r.get("ActivityDate", "") <= "2026-03-29"]
Q_Meetings_PW = [r for r in Q_Meetings_L30 if "2026-03-16" <= r.get("ActivityDate", "") <= "2026-03-22"]

print(f"Q_Meetings_CW: {len(Q_Meetings_CW)} records")
print(f"Q_Meetings_PW: {len(Q_Meetings_PW)} records")

# ── 5. Serialize each array compactly ────────────────────────────────────────
def to_js(data):
    return json.dumps(data, ensure_ascii=False, separators=(',', ':'))

# ── 6. Build JS output ────────────────────────────────────────────────────────
print("Building JS output ...")

js = f"""export default {{

  // \u2500\u2500 Auto-generated by update_quarter.py \u2014 DO NOT EDIT MANUALLY \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500
  data: {{
    'Q1 2026': {{
      quarter:      'Q1 2026',
      snapshotDate: '2026-04-01',
      version:      2,
      queries: {{
        Q_Bookings_QTD:          {to_js(Q_Bookings_QTD)},
        Q_SelfService_QTD:       {to_js(Q_SelfService_QTD)},
        Q_Pipeline_Open:         [],
        Q_Pilots_Open:           [],
        Q_Stale_Pipeline:        [],
        Q_WinLoss:               {to_js(Q_WinLoss)},
        Q_Calls_QTD:             {to_js(Q_Calls_QTD)},
        Q_QualCalls_QTD:         {to_js(Q_QualCalls_QTD)},
        Q_Emails_QTD:            {to_js(Q_Emails_QTD)},
        Q_Meetings_QTD:          {to_js(Q_Meetings_QTD)},
        Q_Quotas:                {to_js(Q_Quotas)},
        Q_Opps_Created_QTD:      {to_js(Q_Opps_Created_QTD)},
        Q_PilotOpps_QTD:         {to_js(Q_PilotOpps_QTD)},
        Q_Demos_QTD:             {to_js(Q_Demos_QTD)},
        Q_Calls_CW:              {to_js(Q_Calls_CW)},
        Q_Calls_PW:              {to_js(Q_Calls_PW)},
        Q_QualCalls_CW:          {to_js(Q_QualCalls_CW)},
        Q_QualCalls_PW:          {to_js(Q_QualCalls_PW)},
        Q_Emails_CW:             {to_js(Q_Emails_CW)},
        Q_Emails_PW:             {to_js(Q_Emails_PW)},
        Q_Meetings_CW:           {to_js(Q_Meetings_CW)},
        Q_Meetings_PW:           {to_js(Q_Meetings_PW)},
        Q_Calls_L30:             {to_js(Q_Calls_L30)},
        Q_QualCalls_L30:         {to_js(Q_QualCalls_L30)},
        Q_Emails_L30:            {to_js(Q_Emails_L30)},
        Q_Meetings_L30:          {to_js(Q_Meetings_L30)},
        Q_Opps_L30:              [],
        Q_Overdue_Pipeline:      [],
        Q_Overdue_Accounts:      [],
        Q_Forecast_Commit:       {to_js(Q_Forecast_Commit)},
        Q_Forecast_Commit_Pilots:{to_js(Q_Forecast_Commit_Pilots)},
      }},
    }},
  }},

}}
"""

# ── 7. Write output ───────────────────────────────────────────────────────────
with open(TARGET, "w", encoding="utf-8") as f:
    f.write(js)

import os
size = os.path.getsize(TARGET)
print(f"\nDone! Written to: {TARGET}")
print(f"File size: {size:,} bytes ({size/1024:.1f} KB)")

# Quick sanity check
with open(TARGET) as f:
    first_line = f.readline().strip()
print(f"First line: {first_line!r}")
